USE PODb;
GO

CREATE TABLE SUPPLIER (
	SUPLNO CHAR(4) PRIMARY KEY,
	SUPLNAME VARCHAR(15) NOT NULL,
	SUPLADDR VARCHAR(40)
)

CREATE TABLE ITEM (
	ITCODE CHAR(4) PRIMARY KEY,
	ITDESC VARCHAR(15) NOT NULL,
	ITRATE MONEY
)

CREATE TABLE POMASTER (
	PONO CHAR(4) PRIMARY KEY,
	PODATE DATETIME,
	SUPLNO CHAR(4) REFERENCES SUPPLIER(SUPLNO)
)

CREATE TABLE PODETAIL (
	PONO CHAR(4) REFERENCES POMASTER(PONO),
	ITCODE CHAR(4) REFERENCES ITEM(ITCODE),
	QTY INT,
	CONSTRAINT POD_PK PRIMARY KEY(PONO, ITCODE)
)