USE PODB;
GO

SELECT * FROM SUPPLIER (NoLock);
SELECT * FROM ITEM (NoLock);
SELECT * FROM POMASTER (NoLock);
SELECT * FROM PODETAIL (NoLock);

/*
DELETE FROM PODETAIL;
DELETE FROM POMASTER;
DELETE FROM ITEM;
DELETE FROM SUPPLIER;
*/

SELECT * FROM SUPPLIER (NoLock);

/*
INSERT INTO SUPPLIER ([SUPLNO], [SUPLNAME], [SUPLADDR]) SELECT dbo.fn_GenPKID ('S', 1), 'SUPPLIER-A', 'CHENNAI';
INSERT INTO SUPPLIER ([SUPLNO], [SUPLNAME], [SUPLADDR]) SELECT dbo.fn_GenPKID ('S', 2), 'SUPPLIER-B', 'MUMBAI';
INSERT INTO SUPPLIER ([SUPLNO], [SUPLNAME], [SUPLADDR]) SELECT dbo.fn_GenPKID ('S', 3), 'SUPPLIER-C', 'DELHI';
INSERT INTO SUPPLIER ([SUPLNO], [SUPLNAME], [SUPLADDR]) SELECT dbo.fn_GenPKID ('S', 4), 'SUPPLIER-D', 'KOLKATTA';
INSERT INTO SUPPLIER ([SUPLNO], [SUPLNAME], [SUPLADDR]) SELECT dbo.fn_GenPKID ('S', 5), 'SUPPLIER-E', 'BANGALORE';
INSERT INTO SUPPLIER ([SUPLNO], [SUPLNAME], [SUPLADDR]) SELECT dbo.fn_GenPKID ('S', 6), 'SUPPLIER-F', 'HYDERABAD';
*/

SELECT * FROM ITEM (NoLock);

/*
INSERT INTO ITEM ([ITCODE], [ITDESC], [ITRATE]) SELECT dbo.fn_GenPKID ('I', 1), 'PEN', '$ 1.25';
INSERT INTO ITEM ([ITCODE], [ITDESC], [ITRATE]) SELECT dbo.fn_GenPKID ('I', 2), 'PENCIL', '$ 0.78';
INSERT INTO ITEM ([ITCODE], [ITDESC], [ITRATE]) SELECT dbo.fn_GenPKID ('I', 3), 'SCALE', '$ 2.45';
INSERT INTO ITEM ([ITCODE], [ITDESC], [ITRATE]) SELECT dbo.fn_GenPKID ('I', 4), 'SCHOOL BAG', '$ 5.15';
INSERT INTO ITEM ([ITCODE], [ITDESC], [ITRATE]) SELECT dbo.fn_GenPKID ('I', 5), 'SHOES', '$ 3.00';
INSERT INTO ITEM ([ITCODE], [ITDESC], [ITRATE]) SELECT dbo.fn_GenPKID ('I', 6), 'BOOK', '$ 4.75';
*/

SELECT * FROM POMASTER (NoLock);

/*
INSERT INTO POMASTER ([PONO], [PODATE], [SUPLNO]) SELECT dbo.fn_GenPKID ('P', 1), '20190615','S001';
INSERT INTO POMASTER ([PONO], [PODATE], [SUPLNO]) SELECT dbo.fn_GenPKID ('P', 2), '20190615','S001';
INSERT INTO POMASTER ([PONO], [PODATE], [SUPLNO]) SELECT dbo.fn_GenPKID ('P', 3), '20190615','S002';
INSERT INTO POMASTER ([PONO], [PODATE], [SUPLNO]) SELECT dbo.fn_GenPKID ('P', 4), '20190622','S001';
INSERT INTO POMASTER ([PONO], [PODATE], [SUPLNO]) SELECT dbo.fn_GenPKID ('P', 5), '20190623','S001';
*/

SELECT * FROM [PODETAIL] (NoLock);

/*
INSERT INTO PODETAIL ([PONO], [ITCODE], [QTY]) VALUES ('P001', 'I001', 2); --P001 (PM) | I001 PEN | 2 - SUP1
INSERT INTO PODETAIL ([PONO], [ITCODE], [QTY]) VALUES ('P002', 'I002', 4); --P002 (PM) | I002 PENCIL | 4 - SUP1
INSERT INTO PODETAIL ([PONO], [ITCODE], [QTY]) VALUES ('P003', 'I001', 8); --P003 (PM) | I001 PEN | 8 - SUP2
INSERT INTO PODETAIL ([PONO], [ITCODE], [QTY]) VALUES ('P004', 'I004', 8); --P004 (PM) | I004 SCHOOL BAG | 10 - SUP1
INSERT INTO PODETAIL ([PONO], [ITCODE], [QTY]) VALUES ('P005', 'I004', 4); --P004 (PM) | I004 SCHOOL BAG | 4 - SUP1
*/

-- SUPPLIER - ITEM - QTY - DATE
--CREATE
--Entry to PO Master
INSERT INTO POMASTER ([PONO], [PODATE], [SUPLNO]) SELECT dbo.fnGenPKID ('P', 1), '20190615','S001';

--Entry to PO Detail
INSERT INTO PODETAIL ([PONO], [ITCODE], [QTY]) VALUES ('P001', 'I001', 2); --P001 (PM) | I001 PEN | 2 - SUP1