USE PODB;
GO

--sql query to get column names from table
SELECT COLUMN_NAME, DATA_TYPE, *
FROM INFORMATION_SCHEMA. COLUMNS
WHERE TABLE_NAME = 'SUPPLIER'
ORDER BY ORDINAL_POSITION;

SELECT COLUMN_NAME, DATA_TYPE, *
FROM INFORMATION_SCHEMA. COLUMNS
WHERE TABLE_NAME = 'ITEM'
ORDER BY ORDINAL_POSITION;

