USE PODb;
GO

--EXEC dbo.sp_GetSupplierRecord

--DROP PROCEDURE sp_GetSupplierRecord

CREATE PROCEDURE dbo.sp_GetSupplierRecord
AS
BEGIN

	SELECT SUPLNO
	 , SUPLNAME 
	FROM dbo.SUPPLIER 
	ORDER BY SUPLNO;

END;
GO

USE PODB;
GO

/*
SELECT * FROM PODB.dbo.SUPPLIER (NoLock);
SELECT SUPLNO, SUPLNAME FROM dbo.SUPPLIER ORDER BY SUPLNO;
SELECT ITCODE, ITDESC FROM dbo.ITEM ORDER BY ITCODE;
*/