//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSE.PO.MVCAPP.PurchaseOrderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseOrderEntity", Namespace="http://schemas.datacontract.org/2004/07/FSE.PO.SVCAPP.Entity")]
    [System.SerializableAttribute()]
    public partial class PurchaseOrderEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PODateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PONoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuplNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuplNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITCode {
            get {
                return this.ITCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ITCodeField, value) != true)) {
                    this.ITCodeField = value;
                    this.RaisePropertyChanged("ITCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITDesc {
            get {
                return this.ITDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ITDescField, value) != true)) {
                    this.ITDescField = value;
                    this.RaisePropertyChanged("ITDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PODate {
            get {
                return this.PODateField;
            }
            set {
                if ((this.PODateField.Equals(value) != true)) {
                    this.PODateField = value;
                    this.RaisePropertyChanged("PODate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PONo {
            get {
                return this.PONoField;
            }
            set {
                if ((object.ReferenceEquals(this.PONoField, value) != true)) {
                    this.PONoField = value;
                    this.RaisePropertyChanged("PONo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuplName {
            get {
                return this.SuplNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SuplNameField, value) != true)) {
                    this.SuplNameField = value;
                    this.RaisePropertyChanged("SuplName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuplNo {
            get {
                return this.SuplNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SuplNoField, value) != true)) {
                    this.SuplNoField = value;
                    this.RaisePropertyChanged("SuplNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/FSE.PO.SVCAPP")]
    [System.SerializableAttribute()]
    public partial class ExceptionMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierEntity", Namespace="http://schemas.datacontract.org/2004/07/FSE.PO.SVCAPP.Entity")]
    [System.SerializableAttribute()]
    public partial class SupplierEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuplAddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuplNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuplNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuplAddr {
            get {
                return this.SuplAddrField;
            }
            set {
                if ((object.ReferenceEquals(this.SuplAddrField, value) != true)) {
                    this.SuplAddrField = value;
                    this.RaisePropertyChanged("SuplAddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuplName {
            get {
                return this.SuplNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SuplNameField, value) != true)) {
                    this.SuplNameField = value;
                    this.RaisePropertyChanged("SuplName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuplNo {
            get {
                return this.SuplNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SuplNoField, value) != true)) {
                    this.SuplNoField = value;
                    this.RaisePropertyChanged("SuplNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemEntity", Namespace="http://schemas.datacontract.org/2004/07/FSE.PO.SVCAPP.Entity")]
    [System.SerializableAttribute()]
    public partial class ItemEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ItRateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItCode {
            get {
                return this.ItCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItCodeField, value) != true)) {
                    this.ItCodeField = value;
                    this.RaisePropertyChanged("ItCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItDesc {
            get {
                return this.ItDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ItDescField, value) != true)) {
                    this.ItDescField = value;
                    this.RaisePropertyChanged("ItDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ItRate {
            get {
                return this.ItRateField;
            }
            set {
                if ((this.ItRateField.Equals(value) != true)) {
                    this.ItRateField = value;
                    this.RaisePropertyChanged("ItRate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PurchaseOrderService.IPurchaseOrderService")]
    public interface IPurchaseOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/ValidateService", ReplyAction="http://tempuri.org/IPurchaseOrderService/ValidateServiceResponse")]
        string ValidateService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/ValidateService", ReplyAction="http://tempuri.org/IPurchaseOrderService/ValidateServiceResponse")]
        System.Threading.Tasks.Task<string> ValidateServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/GetAllPurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseOrderService/GetAllPurchaseOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FSE.PO.MVCAPP.PurchaseOrderService.ExceptionMessage), Action="http://tempuri.org/IPurchaseOrderService/GetAllPurchaseOrderExceptionMessageFault" +
            "", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/FSE.PO.SVCAPP")]
        System.Collections.Generic.List<FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity> GetAllPurchaseOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/GetAllPurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseOrderService/GetAllPurchaseOrderResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity>> GetAllPurchaseOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/GetPurchaseOrderByPONO", ReplyAction="http://tempuri.org/IPurchaseOrderService/GetPurchaseOrderByPONOResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FSE.PO.MVCAPP.PurchaseOrderService.ExceptionMessage), Action="http://tempuri.org/IPurchaseOrderService/GetPurchaseOrderByPONOExceptionMessageFa" +
            "ult", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/FSE.PO.SVCAPP")]
        FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity GetPurchaseOrderByPONO(string poNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/GetPurchaseOrderByPONO", ReplyAction="http://tempuri.org/IPurchaseOrderService/GetPurchaseOrderByPONOResponse")]
        System.Threading.Tasks.Task<FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity> GetPurchaseOrderByPONOAsync(string poNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/CreatePurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseOrderService/CreatePurchaseOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FSE.PO.MVCAPP.PurchaseOrderService.ExceptionMessage), Action="http://tempuri.org/IPurchaseOrderService/CreatePurchaseOrderExceptionMessageFault" +
            "", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/FSE.PO.SVCAPP")]
        int CreatePurchaseOrder(FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity purchaseOrderEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/CreatePurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseOrderService/CreatePurchaseOrderResponse")]
        System.Threading.Tasks.Task<int> CreatePurchaseOrderAsync(FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity purchaseOrderEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/UpdatePurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseOrderService/UpdatePurchaseOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FSE.PO.MVCAPP.PurchaseOrderService.ExceptionMessage), Action="http://tempuri.org/IPurchaseOrderService/UpdatePurchaseOrderExceptionMessageFault" +
            "", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/FSE.PO.SVCAPP")]
        int UpdatePurchaseOrder(FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity purchaseOrderEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/UpdatePurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseOrderService/UpdatePurchaseOrderResponse")]
        System.Threading.Tasks.Task<int> UpdatePurchaseOrderAsync(FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity purchaseOrderEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/DeletePurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseOrderService/DeletePurchaseOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FSE.PO.MVCAPP.PurchaseOrderService.ExceptionMessage), Action="http://tempuri.org/IPurchaseOrderService/DeletePurchaseOrderExceptionMessageFault" +
            "", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/FSE.PO.SVCAPP")]
        int DeletePurchaseOrder(string poNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/DeletePurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseOrderService/DeletePurchaseOrderResponse")]
        System.Threading.Tasks.Task<int> DeletePurchaseOrderAsync(string poNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/GetSupplier", ReplyAction="http://tempuri.org/IPurchaseOrderService/GetSupplierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FSE.PO.MVCAPP.PurchaseOrderService.ExceptionMessage), Action="http://tempuri.org/IPurchaseOrderService/GetSupplierExceptionMessageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/FSE.PO.SVCAPP")]
        System.Collections.Generic.List<FSE.PO.MVCAPP.PurchaseOrderService.SupplierEntity> GetSupplier();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/GetSupplier", ReplyAction="http://tempuri.org/IPurchaseOrderService/GetSupplierResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FSE.PO.MVCAPP.PurchaseOrderService.SupplierEntity>> GetSupplierAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/GetItem", ReplyAction="http://tempuri.org/IPurchaseOrderService/GetItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FSE.PO.MVCAPP.PurchaseOrderService.ExceptionMessage), Action="http://tempuri.org/IPurchaseOrderService/GetItemExceptionMessageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/FSE.PO.SVCAPP")]
        System.Collections.Generic.List<FSE.PO.MVCAPP.PurchaseOrderService.ItemEntity> GetItem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/GetItem", ReplyAction="http://tempuri.org/IPurchaseOrderService/GetItemResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FSE.PO.MVCAPP.PurchaseOrderService.ItemEntity>> GetItemAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchaseOrderServiceChannel : FSE.PO.MVCAPP.PurchaseOrderService.IPurchaseOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseOrderServiceClient : System.ServiceModel.ClientBase<FSE.PO.MVCAPP.PurchaseOrderService.IPurchaseOrderService>, FSE.PO.MVCAPP.PurchaseOrderService.IPurchaseOrderService {
        
        public PurchaseOrderServiceClient() {
        }
        
        public PurchaseOrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseOrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseOrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ValidateService() {
            return base.Channel.ValidateService();
        }
        
        public System.Threading.Tasks.Task<string> ValidateServiceAsync() {
            return base.Channel.ValidateServiceAsync();
        }
        
        public System.Collections.Generic.List<FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity> GetAllPurchaseOrder() {
            return base.Channel.GetAllPurchaseOrder();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity>> GetAllPurchaseOrderAsync() {
            return base.Channel.GetAllPurchaseOrderAsync();
        }
        
        public FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity GetPurchaseOrderByPONO(string poNumber) {
            return base.Channel.GetPurchaseOrderByPONO(poNumber);
        }
        
        public System.Threading.Tasks.Task<FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity> GetPurchaseOrderByPONOAsync(string poNumber) {
            return base.Channel.GetPurchaseOrderByPONOAsync(poNumber);
        }
        
        public int CreatePurchaseOrder(FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity purchaseOrderEntity) {
            return base.Channel.CreatePurchaseOrder(purchaseOrderEntity);
        }
        
        public System.Threading.Tasks.Task<int> CreatePurchaseOrderAsync(FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity purchaseOrderEntity) {
            return base.Channel.CreatePurchaseOrderAsync(purchaseOrderEntity);
        }
        
        public int UpdatePurchaseOrder(FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity purchaseOrderEntity) {
            return base.Channel.UpdatePurchaseOrder(purchaseOrderEntity);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePurchaseOrderAsync(FSE.PO.MVCAPP.PurchaseOrderService.PurchaseOrderEntity purchaseOrderEntity) {
            return base.Channel.UpdatePurchaseOrderAsync(purchaseOrderEntity);
        }
        
        public int DeletePurchaseOrder(string poNo) {
            return base.Channel.DeletePurchaseOrder(poNo);
        }
        
        public System.Threading.Tasks.Task<int> DeletePurchaseOrderAsync(string poNo) {
            return base.Channel.DeletePurchaseOrderAsync(poNo);
        }
        
        public System.Collections.Generic.List<FSE.PO.MVCAPP.PurchaseOrderService.SupplierEntity> GetSupplier() {
            return base.Channel.GetSupplier();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FSE.PO.MVCAPP.PurchaseOrderService.SupplierEntity>> GetSupplierAsync() {
            return base.Channel.GetSupplierAsync();
        }
        
        public System.Collections.Generic.List<FSE.PO.MVCAPP.PurchaseOrderService.ItemEntity> GetItem() {
            return base.Channel.GetItem();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FSE.PO.MVCAPP.PurchaseOrderService.ItemEntity>> GetItemAsync() {
            return base.Channel.GetItemAsync();
        }
    }
}
